// client/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core'

import { events, Event } from '../events'
import { states } from '../states'
import { FormControl } from '@angular/forms'
import { Observable } from 'rxjs'
import { map, startWith } from 'rxjs/operators'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  events: Event[]
  events$: Observable<Event[]>
  filter = new FormControl('')
  nowDate = new Date()

  includes(text, term) {
    if (text) {
      return text.toLowerCase().includes(term.toLowerCase())
    }
    return false
  }

  constructor() {
    this.nowDate.setHours(0, 0, 0, 0)

    // filter out past events
    this.events = events.filter(event => {
      const endDate = new Date(event.endDate)
      endDate.setHours(0, 0, 0, 0)

      return this.nowDate.getTime() <= endDate.getTime()
    })

    // sort by start date
    this.events = this.events.sort((a, b) => {
      const bStart = new Date(parseFloat(a.startDate)) as any
      const aStart = new Date(parseFloat(b.startDate)) as any

      return aStart - bStart
    })

    this.events$ = this.filter.valueChanges.pipe(
      startWith(''),
      map(text => this.search(text))
    )
  }

  search(term: string): Event[] {
    return this.events.filter(event => {
      const state = states.find(st => st.abbreviation === event.location.state)

      return (
        this.includes(event.name, term) ||
        this.includes(event.location.city, term) ||
        this.includes(state.abbreviation, term) ||
        this.includes(state.name, term)
      )
    })
  }

  ngOnInit() {}
}

<div class="row">
  <div class="col">
    <p class="mt-2"></p>
    <div class="jumbotron text-center">
      <h1 class="display-4">homeschool.events</h1>
      <p class="lead">A database of homeschool events.</p>

      <div class="form-group">
        <input
          type="text"
          class="form-control"
          id="search"
          placeholder="Search..."
          [formControl]="filter"
        />
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Type</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">City</th>
          <th scope="col">State</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let event of (events$ | async); index as i">
          <th scope="row">
            <a [href]="event.url">
              <ngb-highlight [result]="event.name" [term]="filter.value">
              </ngb-highlight>
            </a>
          </th>
          <td>
            {{ event.type }}
          </td>
          <td>{{ event.startDate | date: 'longDate' }}</td>
          <td>{{ event.endDate | date: 'longDate' }}</td>
          <td>
            <ngb-highlight [result]="event.location.city" [term]="filter.value">
            </ngb-highlight>
          </td>
          <td>
            <ngb-highlight
              [result]="event.location.state"
              [term]="filter.value"
            >
            </ngb-highlight>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/views/Home.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col">
        <p class="mt-2"></p>
        <div class="jumbotron text-center">
          <h1 class="display-4">homeschool.events</h1>
          <p class="lead">A database of homeschool events. </p>

          <div class="form-group">
            <input v-model="searchText" type="text" class="form-control" id="search" placeholder="Search...">
          </div>

        </div>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">Event</th>
              <th scope="col">Date</th>
              <th scope="col">Location</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="event in filteredList" :key="event.name">
              <th scope="row">
                <a :href="event.url">{{event.name}}</a>
              </th>
              <td>{{event.startDate | moment('MMMM Do YYYY')}} - {{event.endDate | moment('MMMM Do YYYY')}}</td>
              <td>{{event.location.city}}, {{event.location.state}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import { states } from '../states'
import { events } from '../events'

export default {
  name: 'home',
  data: () => {
    return {
      searchText: '',
      events
    }
  },
  computed: {
    filteredList() {
      return this.events.filter(event => {
        const includes = (text) => {
          if (text) {
            return text.toLowerCase().includes(this.searchText.toLowerCase())
          }
          return false
        }

        const state = states.find(state => state.abbreviation === event.location.state)

        return includes(event.name) || includes(event.description) || includes(event.location.city) || includes(state.abbreviation) || includes(state.name)
      })
    }
  }
}
</script>
