// src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core'

import { Event } from '../events'
import { states } from '../states'
import { FormControl } from '@angular/forms'
import { Observable } from 'rxjs'
import { map, startWith } from 'rxjs/operators'
import { ApiService } from '../api.service'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  events: Event[]
  events$: Observable<Event[]>
  filter = new FormControl('')
  nowDate = new Date()

  defaultImg = 'assets/blank.svg'

  constructor(private api: ApiService) {}

  includes(text, term) {
    if (text) {
      return text.toLowerCase().includes(term.toLowerCase())
    }
    return false
  }

  search(term: string): Event[] {
    if (!this.events) {
      return
    }

    return this.events.filter(event => {
      const state = states.find(st => st.abbreviation === event.location.state)

      return (
        this.includes(event.name, term) ||
        this.includes(event.location.city, term) ||
        this.includes(state.abbreviation, term) ||
        this.includes(state.name, term)
      )
    })
  }

  ngOnInit() {
    this.nowDate.setHours(0, 0, 0, 0)

    this.getData()
  }

  getData() {
    this.api.getEvents().subscribe((events: Event[]) => {
      for (const event of events) {
        const domain = new URL(event.url).hostname

        event.logo = `https://logo.clearbit.com/${domain}`
      }

      // filter out past events
      this.events = events.filter(event => {
        const endDate = new Date(event.endDate)
        endDate.setHours(0, 0, 0, 0)

        return this.nowDate.getTime() <= endDate.getTime()
      })

      // sort by start date
      this.events = this.events.sort((a, b) => {
        return (
          (new Date(parseFloat(b.startDate)) as any) -
          (new Date(parseFloat(a.startDate)) as any)
        )
      })

      this.events$ = this.filter.valueChanges.pipe(
        startWith(''),
        map(text => this.search(text))
      )
    })
  }
}

<header>
  <div class="row mt-3">
    <div class="col">
      <h1 class="display-4">homeschool.events</h1>
      <p class="lead">A database of homeschool events</p>

      <a [routerLink]="['/submit']" class="btn btn-primary btn-raised">
        Submit an event
      </a>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <input
        type="text"
        class="form-control mt-3"
        id="search"
        placeholder="Search..."
        [formControl]="filter"
      />
    </div>
  </div>
</header>

<div class="row mb-5">
  <div
    class="col-md-4 col-sm-6 col-xs-12 mb-4"
    *ngFor="let event of events$ | async; index as i"
  >
    <div class="card h-100 text-center event-card">
      <a
        [href]="event.url"
        class="card-body p-4 event-link h-100 d-flex flex-column justify-content-between align-items-center"
      >
        <img
          [src]="event.logo"
          [alt]="event.name + ' logo'"
          class="event-logo"
          (error)="img.src = defaultImg"
          #img
        />

        <h5 class="card-title">
          {{ event.name }}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ event.startDate | date: 'MMM d' }} -
          {{ event.endDate | date: 'mediumDate' }}
          - <b>{{ event.type }}</b>
        </h6>

        <p class="card-text">
          {{ event.location.city }},
          {{ event.location.state }}
        </p>
      </a>
    </div>
  </div>
</div>

// src/views/Home.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col">
        <p class="mt-2"></p>
        <div class="jumbotron text-center">
          <h1 class="display-4">homeschool.events</h1>
          <p class="lead">A database of homeschool events.</p>

          <div class="form-group">
            <input
              v-model="searchText"
              type="text"
              class="form-control"
              id="search"
              placeholder="Search..."
            >
          </div>
        </div>

        <b-table
          :sort-by.sync="sortBy"
          :sort-desc.sync="sortDesc"
          :fields="fields"
          :items="filteredList"
        >
          <!-- A custom formatted column -->
          <template slot="name" slot-scope="data">
            <a :href="data.item.url">{{data.item.name}}</a>
          </template>

          <template
            slot="startDate"
            slot-scope="data"
          >{{data.item.startDate | moment('MMMM Do YYYY')}}</template>

          <template slot="endDate" slot-scope="data">{{data.item.endDate | moment('MMMM Do YYYY')}}</template>
        </b-table>
      </div>
    </div>
  </div>
</template>

<script>
import { states } from '../states'
import { events } from '../events'

export default {
  name: 'home',
  data: () => {
    return {
      searchText: '',
      events,
      sortBy: 'startDate',
      sortDesc: false,
      fields: [
        {
          label: 'Event',
          key: 'name',
          sortable: true
        },
        {
          label: 'Start Date',
          key: 'startDate',
          sortable: true
        },
        {
          label: 'End Date',
          key: 'endDate',
          sortable: true
        },
        {
          label: 'City',
          key: 'location.city',
          sortable: true
        },
        {
          label: 'State',
          key: 'location.state',
          sortable: true
        }
      ]
    }
  },
  computed: {
    filteredList () {
      return this.events.filter(event => {
        const includes = text => {
          if (text) {
            return text.toLowerCase().includes(this.searchText.toLowerCase())
          }
          return false
        }

        const state = states.find(
          state => state.abbreviation === event.location.state
        )

        return (
          includes(event.name) ||
          includes(event.description) ||
          includes(event.location.city) ||
          includes(state.abbreviation) ||
          includes(state.name)
        )
      })
    }
  }
}
</script>
