// src/views/Submit.vue
<template>
  <div class="container mt-2">
    <div class="row">
      <div class="col">
        <h1>Submit an event</h1>

        <form id="submitForm" @submit.prevent="submitEvent">
          <div class="form-group">
            <label for="name">Name</label>
            <input v-model="event.name" type="text" class="form-control" id="name" required>
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <textarea v-model="event.description" class="form-control" id="description" rows="3"></textarea>
          </div>

          <div class="form-group">
            <label for="startDate">Start Date</label>
            <datepicker v-model="event.startDate" bootstrap-styling name="startDate" format="MMM dd yyyy" required></datepicker>

          </div>
          <div class="form-group">
            <label for="endDate">End Date</label>
            <datepicker v-model="event.endDate" bootstrap-styling name="endDate" format="MMM dd yyyy" required></datepicker>
          </div>

          <div class="form-group">
            <label for="city">City</label>
            <input v-model="event.city" type="text" class="form-control" id="city" required>
          </div>
          <div class="form-group">
            <label for="state">State</label>
            <select v-model="event.state" class="form-control" id="state" required>
              <option v-for="state in states" :key="state.abbreviation" v-bind:value="state.abbreviation">{{state.name}}</option>
            </select>
          </div>

          <button type="submit" class="btn btn-raised btn-success">Submit</button>
        </form>

      </div>
    </div>
  </div>
</template>

<script>
import Datepicker from 'vuejs-datepicker';

import { states } from '../states'

export default {
  name: 'submit',
  components: {
    Datepicker
  },
  methods: {
    submitEvent() {
      console.log(this.event)
    }
  },
  data: () => {
    return {
      states,
      event: {
        name: '',
        description: '',
        startDate: '',
        endDate: '',
        city: '',
        state: ''
      }
    }
  }
}
</script>

// client/src/app/submit/submit.component.ts
import { Component, OnInit } from '@angular/core'
import { states } from '../states'

import {
  FormGroup,
  FormControl,
  Validators,
  AbstractControl
} from '@angular/forms'

@Component({
  selector: 'app-submit',
  templateUrl: './submit.component.html',
  styleUrls: ['./submit.component.scss']
})
export class SubmitComponent implements OnInit {
  states: any

  form: FormGroup

  name: AbstractControl
  url: AbstractControl
  startDate: AbstractControl
  endDate: AbstractControl
  type: AbstractControl
  city: AbstractControl
  state: AbstractControl

  constructor() {
    this.states = states
  }

  onSubmit() {
    console.log(this.form.value)
  }

  ngOnInit() {
    this.form = new FormGroup({
      name: new FormControl(null, [
        Validators.required,
        Validators.maxLength(200)
      ]),
      url: new FormControl(null, []),
      startDate: new FormControl(null, [Validators.required]),
      endDate: new FormControl(null, [Validators.required]),
      type: new FormControl(null, [Validators.required]),
      city: new FormControl(null, [Validators.required]),
      state: new FormControl(null, [Validators.required])
    })

    this.name = this.form.controls.name
    this.url = this.form.controls.url
    this.startDate = this.form.controls.startDate
    this.endDate = this.form.controls.endDate
    this.type = this.form.controls.type
    this.city = this.form.controls.city
    this.state = this.form.controls.state
  }
}

<div class="row mt-2">
  <div class="col">
    <h1>Submit an event</h1>

    <form id="submitForm" (ngSubmit)="onSubmit()" [formGroup]="form" novalidate>
      <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          formControlName="name"
        />
      </div>

      <div class="form-group">
        <label for="url">URL</label>
        <input
          type="text"
          class="form-control"
          id="url"
          formControlName="url"
        />
      </div>

      <div class="form-group">
        <label for="type">Type</label>
        <select class="form-control" id="type" formControlName="type">
          <option value="Convention" [selected]="true">Convention</option>
        </select>
      </div>

      <!--<div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" rows="3"></textarea>
      </div> -->

      <div class="form-group">
        <label for="startDate">Start Date</label>
        <input
          type="datetime-local"
          class="form-control"
          name="startDate"
          formControlName="startDate"
        />
      </div>

      <div class="form-group">
        <label for="endDate">End Date</label>
        <input
          type="date"
          class="form-control"
          name="endDate"
          formControlName="endDate"
        />
      </div>

      <div class="form-group">
        <label for="city">City</label>
        <input
          type="text"
          class="form-control"
          id="city"
          formControlName="city"
        />
      </div>

      <div class="form-group">
        <label for="state">State</label>
        <select class="form-control" id="state" formControlName="state">
          <option *ngFor="let state of states" [value]="state.abbreviation">
            {{ state.name }}
          </option>
        </select>
      </div>

      <button
        type="submit"
        class="btn btn-raised btn-success"
        [disabled]="!form.valid"
      >
        Submit
      </button>
    </form>
  </div>
</div>
