// client/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  year = new Date().getFullYear()
}

<div class="d-flex flex-column h-100">
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
      <a class="navbar-brand" [routerLink]="['/']">homeschool.events</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" [routerLink]="['/']" routerLinkActive="active">
              Home
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              [routerLink]="['/submit']"
              routerLinkActive="active"
            >
              Submit
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>

  <main role="main" class="flex-shrink-0">
    <div class="container">
      <router-outlet></router-outlet>
    </div>
  </main>

  <footer class="footer mt-auto py-3">
    <div class="container">
      <span class="text-muted">
        Created by <a href="https://e1.lc/tAfSUQ">eventOne</a> -
        <a href="https://github.com/eventOneHQ/homeschool.events">
          Open Source
        </a>
      </span>
      <span class="text-muted float-right">
        &copy; {{ year }} eventOne, Inc.
      </span>
    </div>
  </footer>
</div>

// src/App.vue
<template>
  <div id="app" class="d-flex flex-column h-100">
    <div>
      <b-navbar toggleable="lg" type="dark" variant="success">
        <b-navbar-brand to="/">homeschool.events</b-navbar-brand>

        <b-navbar-toggle target="nav_collapse"/>

        <b-collapse is-nav id="nav_collapse">
          <b-navbar-nav>
            <b-nav-item to="/">Home</b-nav-item>
            <b-nav-item to="/submit">Submit</b-nav-item>
          </b-navbar-nav>
        </b-collapse>
      </b-navbar>
    </div>

    <main role="main" class="flex-shrink-0">
      <router-view/>
    </main>

    <footer class="footer mt-auto py-3">
      <div class="container">
        <span class="text-muted">Created by <a href="https://e1.lc/tAfSUQ">eventOne</a> - <a href="https://github.com/eventOneHQ/homeschool.events">Open Source</a></span>
        <span class="text-muted float-right">&copy; {{new Date().getFullYear()}} eventOne, Inc.</span>
      </div>
    </footer>
  </div>
</template>

<style>
.footer {
  background-color: #f5f5f5;
}
</style>
